version: '2'
services:
  solr:
    build: ../solr
    ports:
     - "8983:8983"
    # repos-indexing is designed to re-index as needed; no need to make solr data persistent
    #volumes:
    #  # data dir should be group-writable
    #  - ./data/solr:/solrdata
  svn:
    build: ./svn
    ports:
     - "80:80"
    volumes:
     - ./data/svn:/svn
    # unless you already have repositories in ./data/svn do something like: docker-compose run svn repocreate test1
  indexing:
    build: ../indexing-svnlook
    volumes:
     - ./data/svn:/svn
    links:
      - svn:svn
      - solr:solr
    command:
      - -d
      - /svn
      - -e
      - http://svn/svn/
      - -s
      - http://solr:8983/solr/
