apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
  # labels applied automatically from pod template
spec:
  replicas: 1
  # selector applied automatically from pod template
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        image: solsson/repos-indexing-solr@sha256:3f77712ee78e66da39a46295170ac94cd67f37fa56cd560ca7e22344d372062e
        ports:
        - containerPort: 8983