apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: svn
spec:
  serviceName: "svn"
  replicas: 1
  template:
    metadata:
      labels:
        app: svn
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: svn
        image: solsson/rweb-httpd@sha256:676f12d8125fc5a8a50bb21778628b831a4052c66d1508b587433424683708db
        ports:
        - name: http
          containerPort: 80
        env:
        - name: AUTHN
          value: anon
        - name: ADMIN_REST_ACCESS
          value: "true"
        volumeMounts:
        - name: datadir
          mountPath: /svn
      - name: rweb
        image: solsson/rweb@sha256:c39b35eb6dc65c1baa165eb6635f16375354328a7edd481927ad12db4a89b6fc
        ports:
        - name: rweb
          containerPort: 9000
  volumeClaimTemplates:
  - metadata:
      name: datadir
