apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svn
  # labels applied automatically from pod template
spec:
  replicas: 1
  # selector applied automatically from pod template
  template:
    metadata:
      labels:
        app: svn
    spec:
      containers:
      - name: svn
        image: solsson/svn-httpd:1.8.16
        ports:
        - containerPort: 80
      - name: indexing
        image: solsson/repos-indexing-svnlook@sha256:52321e6196324f188bd18da8ee31a0a388b528bbfe74c8899ae995391d727c82
        args:
        - -d
        - /svn
        - -e
        - http://svn/svn/
        - -s
        - http://solr:8983/solr/
      #TODO- name: rweb