---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-svn-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      site: repos-indexing-example
      persist: svn
